name: CI/CD pipeline

on: #
  push:
    branches:
      - main
jobs: #
  build-and-test:
    runs-on: ubuntu-latest #
    steps: #
      - name: Checkout repository #
        uses: actions/checkout@v6 #

      - name: Instalar dependencias
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest #
    if: success()
    steps:
      - name: Despregamento en produción #
        run: echo "Despregando a aplicación..."
