name: Granxa Animales Node.js #

on: #
  push:
    branches:
      - main
jobs: #
  build:
    runs-on: ubuntu-latest #
    steps: #
      - name: Checkout repository #
        uses: actions/checkout@v6 #

      - name: Instalar dependencias
        run: npm install

      - name: Run tests
        run: npm test
